# Generated by Django 5.0.7 on 2024-09-03 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_category_options_alter_subtask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_manager_subtasks', to=settings.AUTH_USER_MODEL),
            preserve_default=True,  # Сохраняем значение по умолчанию
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='task_manager_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=True,  # Сохраняем значение по умолчанию
        ),
    ]