# Generated by Django 5.0.7 on 2024-08-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
