# Generated by Django 5.0.7 on 2024-08-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-title'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'description')},
        ),
    ]
