# Generated by Django 5.0.7 on 2024-08-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0004_projectfile_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='Projects'),
        ),
    ]
