# Generated by Django 5.0.7 on 2024-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0005_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='project_tasks.projectfile'),
        ),
    ]
